### ISSUE TITLE
Calendar date selection 

### ISSUE THREAD

**Issue by Christinanine** [gshotwell/shambhala_dashboard#8]
Hi Gordon, I'm web admin/publicity person with Santa Rosa Shambhala. As you're adding features, it would be great to have an arrow to change by year on the calendar chooser. Right now, you can only change months.  Thanks! Christina

**Comment by gshotwell** [comment]
You can actually change it by year. Just click on the date box, then click on the month, it will then switch to the annual calendar. You can also type in any date you want into the box.  Does that fix the problem?

**Comment by Christinanine** [comment]
Hi Gordon,
Ahh, got it. I was expecting it to have the little double-arrow like on 
the SDB. Thanks :-)  Cool that you're doing this!
Christina

GShotwell wrote:
